//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.datacontract.org/2004/07/OLDB.Spa.Models.Api")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.datacontract.org/2004/07/OLDB.Spa.Models.Api", IsNullable=false)]
public partial class ArrayOfTeam {
    
    private ArrayOfTeamTeam[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Team")]
    public ArrayOfTeamTeam[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.datacontract.org/2004/07/OLDB.Spa.Models.Api")]
public partial class ArrayOfTeamTeam {
    
    private string shortNameField;
    
    private string teamIconUrlField;
    
    private string teamIdField;
    
    private string teamNameField;
    
    /// <remarks/>
    public string ShortName {
        get {
            return this.shortNameField;
        }
        set {
            this.shortNameField = value;
        }
    }
    
    /// <remarks/>
    public string TeamIconUrl {
        get {
            return this.teamIconUrlField;
        }
        set {
            this.teamIconUrlField = value;
        }
    }
    
    /// <remarks/>
    public string TeamId {
        get {
            return this.teamIdField;
        }
        set {
            this.teamIdField = value;
        }
    }
    
    /// <remarks/>
    public string TeamName {
        get {
            return this.teamNameField;
        }
        set {
            this.teamNameField = value;
        }
    }
}
