//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.datacontract.org/2004/07/OLDB.Spa.Models.Api")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.datacontract.org/2004/07/OLDB.Spa.Models.Api", IsNullable=false)]
public partial class Group {
    
    private string groupIDField;
    
    private string groupNameField;
    
    private string groupOrderIDField;
    
    /// <remarks/>
    public string GroupID {
        get {
            return this.groupIDField;
        }
        set {
            this.groupIDField = value;
        }
    }
    
    /// <remarks/>
    public string GroupName {
        get {
            return this.groupNameField;
        }
        set {
            this.groupNameField = value;
        }
    }
    
    /// <remarks/>
    public string GroupOrderID {
        get {
            return this.groupOrderIDField;
        }
        set {
            this.groupOrderIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.datacontract.org/2004/07/OLDB.Spa.Models.Api")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.datacontract.org/2004/07/OLDB.Spa.Models.Api", IsNullable=false)]
public partial class NewDataSet {
    
    private Group[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Group")]
    public Group[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
